// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    Animation: typeof import('./src/components/animation/animation.vue')['default']
    BaseInput: typeof import('./src/components/input/base-input.tsx')['default']
    Image: typeof import('./src/components/image/src/image.vue')['default']
    Input: typeof import('./src/components/input/input.tsx')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SvgBack: typeof import('./src/components/svg/svg-back.tsx')['default']
    Tinymce: typeof import('./src/components/editor/tinymce/tinymce.vue')['default']
  }
}
